### PR TITLE
Added celery_task_runtime metric

### PR DESCRIPTION
**Pull request by spankratov**
Hi Dani,

Thanks for your great library! I’d like to contribute one simple metric that I felt was missing. It’s simple Histogram which tracks runtime that celery sends with task-succeeded event. I also added one optional CLI argument, ‘buckets’, for histogram buckets initialization. I hope you find it useful. Looking forward to your comments if something’s off in the code.

### CODE REVIEW

**Comment by danihodovic** [comment]
Good stuff, what do you think about adding bucket defaults to the click options? That makes it visible in the cli.

`default=Histogram.DEFAULT_BUCKETS`

**Comment by spankratov** [comment]
Good point. I've pushed the commit. I made `Histogram.DEFAULT_BUCKETS` a string because the help text is misleading if default value is a tuple of floats:
```
--buckets <FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT FLOAT>...
                                  Buckets for runtime histogram, e.g
                                  '0.005,0.01,inf'  [default: 0.005, 0.01,
                                  0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75,
                                  1.0, 2.5, 5.0, 7.5, 10.0, inf]
```

**Review by danihodovic — APPROVED** [review]
Squash, merge and I will push a new latest release.

**Comment by spankratov** [comment]
Great, thanks! Can you please squash my commits during the merge? I merged your last changes from master branch before squashing my branch and I'm not sure how I can do the squash properly right now.

**Comment by danihodovic** [comment]
I've updated the latest release.

**Pull request merged**
