### PR TITLE
fix: update deps with cves

### PR DESCRIPTION
**Pull request by wyattw-orca**
Per #295, this updates vulnerable versions of pyinstaller and certifi.

### CODE REVIEW

**Comment by danihodovic** [comment]
Thanks

**Comment by danihodovic** [comment]
Released as docker.io/danihodovic/celery-exporter:0.10.3

**Comment by wyattw-orca** [comment]
Thank you so much!

**Comment by wyattw-orca** [comment]
@danihodovic I don't see the image in Docker Hub yet, is there a delay before it shows up there?

**Comment by danihodovic** [comment]
It seems like my push yesterday was aborted. I'll push it tomorrow.

**Comment by danihodovic** [comment]
It should be there now https://hub.docker.com/layers/danihodovic/celery-exporter/0.10.3/images/sha256-c183eac7ea399affe211b3345035a13bdff96936a41fac003bca5f6c216216e7?context=explore

**Comment by wyattw-orca** [comment]
Fantastic! I really appreciate all the help.

**Pull request merged**
