### PR TITLE
Add support to bind on host address

### PR DESCRIPTION
**Pull request by steinbrueckri**
Hi, @danihodovic would be fantastic if you merged it so that you also make a new release. I have not extended the tests, but it does not need it because otherwise has not changed and it is still the default.

### CODE REVIEW

**Comment by danihodovic** [comment]
Fix the test suite and we'll merge it

**Comment by steinbrueckri** [comment]
@danihodovic Pytest is fixed, sorry I forgot about that.

**Review by danihodovic — APPROVED** [review]

**Comment by danihodovic** [comment]
Danke Herr Steinbrück. Veröffentlichte als danihodovic/celery-exporter:0.7.4

**Comment by steinbrueckri** [comment]
Hi, @danihodovic I need to ping you again because of the release, I have seen you have released a new version of the container image but no new GitHub release. Can you please release the master also as 0.7.4 with a GitHub Release?

**Comment by danihodovic** [comment]
The release process is a mess right now. We're mainly using it to create helm releases. Do you need the python binary or a docker container? 0.7.4 exists on Docker Hub - https://hub.docker.com/r/danihodovic/celery-exporter/tags.

**Comment by steinbrueckri** [comment]
> The release process is a mess right now. We're mainly using it to create helm releases. Do you need the python binary or a docker container? 0.7.4 exists on Docker Hub - https://hub.docker.com/r/danihodovic/celery-exporter/tags.

python binary is the best for my use case. But never mind at the moment I have a self build version, I will try to create a PR for better releases. 😅

**Pull request merged**
